FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@10.17.1 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps/jobs ./apps/jobs
RUN pnpm install --filter @tc/jobs...

FROM deps AS build
ARG MODE=production
ENV NODE_ENV=$MODE
RUN pnpm --filter @tc/jobs build

FROM node:22-alpine AS prod
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@10.17.1 --activate
WORKDIR /app
ARG MODE=production
ENV NODE_ENV=$MODE
COPY --from=build /app /app
CMD ["pnpm", "--filter", "@tc/jobs", "start"]
